- hosts: all
  remote_user: "{{ BECOME_USER }}"
  become: yes
  become_method: sudo

  tasks:

  - name: "Insertar domain en fichero ifcfg-eth0"
    lineinfile: path=/etc/sysconfig/network-scripts/ifcfg-eth0 line='DOMAIN={{DOMAINTWO}}'


  - name: "Añadir la search en fichero ifcfg-eth0"
    lineinfile: path=/etc/sysconfig/network-scripts/ifcfg-eth0 line='SEARCH={{DOMAINTWO}}'
