- hosts: all
  remote_user: "{{ BECOME_USER }}"
  become: yes
  become_method: sudo

  tasks:
  - name: "Instalar paquete libselinux-python"
    yum: name=libselinux-python state=present

  - name: "Añadir disabled en ficchero SELINUX"
    selinux: state=disabled

  #- name: "enforcing"
  #  command: "setenforce 0"
  #  ignore_errors: yes

  - name: "Cambio Time zone Europe/Madrid"
    timezone:
        name: Europe/Madrid
