- hosts: all
  remote_user: "{{ BECOME_USER }}"
  become: yes
  become_method: sudo

  tasks:

  - name: "Instalar servicio rsyslog"
    yum:
      name: rsyslog
      state: latest

  - name: "Agregar opcion off en syslog en lista servicios "
    command: /sbin/chkconfig syslog off
    ignore_errors: yes

  - name: "Agregar opcion on en rsyslog en lista servicios "
    command: /sbin/chkconfig rsyslog on

  - name: "Insertar vars en fichero rsyslog"
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^auth,user.* /var/log/messages'
      line: 'auth,user.* /var/log/messages'
      state: present

  - name: "Insertar vars en fichero rsyslog"
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^kern.* /var/log/kern.log'
      line: 'kern.* /var/log/kern.log'
      state: present

  - name: "Insertar vars en fichero rsyslog"
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^daemon.* /var/log/daemon.log'
      line: 'daemon.* /var/log/daemon.log'
      state: present

  - name: "Insertar vars en fichero rsyslog"
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^syslog.* /var/log/syslog'
      line: 'syslog.* /var/log/syslog'
      state: present

  - name: "Insertar vars en fichero rsyslog"
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^lpr,news,uucp,local0,local1,local2,local3,local4,local5,local6.* /var/log/unused.log'
      line: 'lpr,news,uucp,local0,local1,local2,local3,local4,local5,local6.* /var/log/unused.log'
      state: present

  - name: "Insertar vars en fichero rsyslog"
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: 'ModLoad imtcp.so$'
      line: '$ModLoad imtcp.so'
      state: present

  - name: "Insertar vars en fichero rsyslog"
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: 'InputTCPServerRun 514$'
      line: '$InputTCPServerRun 514'
      state: present

  - name: "Restar servicio rsyslog"
    service:
      name: rsyslog
      state: restarted

  
