- hosts: all
  remote_user: "{{ BECOME_USER }}"
  become: yes
  become_method: sudo

  tasks:
  - name: "Copy fichero passwd y shadow en otra ruta local"
    archive:
      path:
        - /etc/passwd
        - /etc/shadow
      dest: /root/bkup_passwd_shadow.tar.gz

  - name: "Copy fichero sshd en otra ruta local"
    archive:
      path:
        - /etc/ssh/sshd_config
      dest: /root/bkup_sshd_conf.tar.gz

  - name: "Copy fichero su en otra ruta local"
    archive:
      path:
        - /etc/pam.d/su
      dest: /root/bkup_pam_su.tar.gz

  - name: "Copy fichero sshd en otra ruta local"
    archive:
      path:
        - /etc/sysctl.conf
      dest: /root/bkup_sysctl_conf.tar.gz

  - name: "Copy fichero grub en otra ruta local"
    archive:
      path:
        - /etc/grub.conf
      dest: /root/bkup_grub_conf.tar.gz

  - name: "Copy fichero audit en otra ruta local"
    archive:
      path:
        - /etc/audit/auditd.conf
      dest: /root/bkup_auditd_conf.tar.gz

  - name: "Copy fichero audit rules en otra ruta local"
    archive:
      path:
        - /etc/audit/audit.rules
      dest: /root/bkup_audit_rules.tar.gz
