- hosts: all
  remote_user: "{{ BECOME_USER }}"
  become: yes
  become_method: sudo

  tasks:

  - name: "Insertar vars en fichero audit"
    lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^max_log_file ='
      line: 'max_log_file = 6'
      state: present

  - name: "Insertar vars en fichero audit"
    lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^space_left_action'
      line: 'space_left_action = SYSLOG'
      state: present

  - name: "Insertar vars en fichero audit"
    lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^action_mail_acct'
      line: 'action_mail_acct = root'
      state: present

  - name: "Insertar vars en fichero audit"
    lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^admin_space_left_action'
      line: 'admin_space_left_action = halt'
      state: present

  - name: "Insertar vars en fichero audit"
    lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^max_log_file_action'
      line: 'max_log_file_action = keep_logs'
      state: present

  - name: "Agregar opcion on en audit en lista servicios "
    command: /sbin/chkconfig auditd on

  - name: "Insertar vars en fichero grub.conf"
    lineinfile:
      path: /etc/grub.conf
      backup: True
      backrefs: True
      state: present
      regexp: '(^\s+kernel(\s+(?!audit=1)[\w=/\-\.]+)*)\s*$'
      line: '\1 audit=1'

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change'
      line: '-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change'
      line: '-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b64 -S clock_settime -k time-change'
      line: '-a always,exit -F arch=b64 -S clock_settime -k time-change'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b32 -S clock_settime -k time-change'
      line: '-a always,exit -F arch=b32 -S clock_settime -k time-change'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /etc/localtime -p wa -k time-change'
      line: '-w /etc/localtime -p wa -k time-change'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /etc/group -p wa -k identity'
      line: '-w /etc/group -p wa -k identity'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /etc/passwd -p wa -k identity'
      line: '-w /etc/passwd -p wa -k identity'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /etc/gshadow -p wa -k identity'
      line: '-w /etc/gshadow -p wa -k identity'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /etc/shadow -p wa -k identity'
      line: '-w /etc/shadow -p wa -k identity'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /etc/security/opasswd -p wa -k identity'
      line: '-w /etc/security/opasswd -p wa -k identity '
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-locale'
      line: '-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-locale'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b32 -S sethostname -S setdomainname -k system-locale'
      line: '-a always,exit -F arch=b32 -S sethostname -S setdomainname -k system-locale'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /etc/issue -p wa -k system-locale'
      line: '-w /etc/issue -p wa -k system-locale'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /etc/issue.net -p wa -k system-locale'
      line: '-w /etc/issue.net -p wa -k system-locale'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /etc/hosts -p wa -k system-locale'
      line: '-w /etc/hosts -p wa -k system-locale'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /etc/sysconfig/network -p wa -k system-locale'
      line: '-w /etc/sysconfig/network -p wa -k system-locale'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /etc/selinux/ -p wa -k MAC-policy'
      line: '-w /etc/selinux/ -p wa -k MAC-policy'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /var/log/faillog -p wa -k logins'
      line: '-w /var/log/faillog -p wa -k logins'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /var/log/lastlog -p wa -k logins'
      line: '-w /var/log/lastlog -p wa -k logins'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /var/log/tallylog -p wa -k logins'
      line: '-w /var/log/tallylog -p wa -k logins'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /var/run/utmp -p wa -k session'
      line: '-w /var/run/utmp -p wa -k session'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /var/log/wtmp -p wa -k session'
      line: '-w /var/log/wtmp -p wa -k session'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /var/log/btmp -p wa -k session'
      line: '-w /var/log/btmp -p wa -k session'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=500 -F auid!=4294967295 -k perm_mod'
      line: '-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=500 -F auid!=4294967295 -k perm_mod'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=500 -F auid!=4294967295 -k perm_mod'
      line: '-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=500 -F auid!=4294967295 -k perm_mod'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=500 -F auid!=4294967295 -k perm_mod'
      line: '-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=500 -F auid!=4294967295 -k perm_mod'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown A125 -F auid>=500 -F auid!=4294967295 -k perm_mod'
      line: '-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown A125 -F auid>=500 -F auid!=4294967295 -k perm_mod'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=500 -F auid!=4294967295 -k perm_mod'
      line: '-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=500 -F auid!=4294967295 -k perm_mod'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=500 -F auid!=4294967295 -k perm_mod'
      line: '-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=500 -F auid!=4294967295 -k perm_mod'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=500 -F auid!=4294967295 -k access'
      line: '-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=500 -F auid!=4294967295 -k access'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=500 -F auid!=4294967295 -k access'
      line: '-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=500 -F auid!=4294967295 -k access'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=500 -F auid!=4294967295 -k access'
      line: '-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=500 -F auid!=4294967295 -k access'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=500 -F auid!=4294967295 -k access'
      line: '-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=500 -F auid!=4294967295 -k access'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b64 -S mount -F auid>=500 -F auid!=4294967295 -k mounts'
      line: '-a always,exit -F arch=b64 -S mount -F auid>=500 -F auid!=4294967295 -k mounts'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b32 -S mount -F auid>=500 -F auid!=4294967295 -k mounts'
      line: '-a always,exit -F arch=b32 -S mount -F auid>=500 -F auid!=4294967295 -k mounts'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete'
      line: '-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete'
      line: '-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /sbin/insmod -p x -k modules'
      line: '-w /sbin/insmod -p x -k modules'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /sbin/rmmod -p x -k modules'
      line: '-w /sbin/rmmod -p x -k modules'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /sbin/modprobe -p x -k modules'
      line: '-w /sbin/modprobe -p x -k modules'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /etc/sudoers -p wa -k scope'
      line: '-w /etc/sudoers -p wa -k scope'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-w /var/log/sudo.log -p wa -k actions'
      line: '-w /var/log/sudo.log -p wa -k actions'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-a always,exit -F arch=b64 -S init_module -S delete_module –k modules'
      line: '-a always,exit -F arch=b64 -S init_module -S delete_module –k modules'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-F path=" $1 " - will populate each file name found through the find command and processed by awk.'
      line: '-F path=" $1 " - will populate each file name found through the find command and processed by awk.'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-F perm=x - will write an audit record if the file is executed.'
      line: '-F perm=x - will write an audit record if the file is executed.'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-F auid>=500 - will write a record if the user executing the command is not a privileged user.'
      line: '-F auid>=500 - will write a record if the user executing the command is not a privileged user.'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-F auid!= 4294967295 - will ignore Daemon events.'
      line: '-F auid!= 4294967295 - will ignore Daemon events.'
      state: present

  - name: "Insertar vars en fichero audit rules"
    lineinfile:
      path: /etc/audit/audit.rules
      regexp: '^-e 2'
      line: '-e 2'
      state: present

  - name: "Reiniciar servicio auditd"
    service: name=auditd state=restarted
