- hosts: all
  remote_user: "{{ BECOME_USER }}"
  become: yes
  become_method: sudo

  tasks:

  - name: "Insertar vars en fichero audit"
    lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^max_log_file ='
      line: 'max_log_file = 6'
      state: present

  - name: "Insertar vars en fichero audit"
    lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^space_left_action'
      line: 'space_left_action = SYSLOG'
      state: present

  - name: "Insertar vars en fichero audit"
    lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^action_mail_acct'
      line: 'action_mail_acct = root'
      state: present

  - name: "Insertar vars en fichero audit"
    lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^admin_space_left_action'
      line: 'admin_space_left_action = halt'
      state: present


  - name: "Insertar vars en fichero audit"
    lineinfile:
      path: /etc/audit/auditd.conf
      regexp: '^max_log_file_action'
      line: 'max_log_file_action = keep_logs'
      state: present
