- hosts: all
  remote_user: "{{ BECOME_USER }}"
  become: yes
  become_method: sudo

  tasks:

  - name: "Insertar en ficheros /etc/ssh/sshd AllowUsers"
    lineinfile: path=/etc/ssh/sshd_config line='AllowUsers={{BECOME_USER}}'
