- hosts: all
  remote_user: "{{ BECOME_USER }}"
  become: yes
  become_method: sudo

  tasks:

  - name: "Instalar servicio rsyslog"
    yum:
      name: rsyslog
      state: latest

  - name: "Agregar opcion off en syslog en lista servicios "
    command: /sbin/chkconfig syslog off

  - name: "Agregar opcion on en rsyslog en lista servicios "
    command: /sbin/chkconfig rsyslog on
