- hosts: workers
  remote_user: bismart
  become: yes
  become_method: sudo

  tasks:

 - name: "Reemplazar fichero krb5"
   template: src=/home/bismart/test-ansible/templates/krb5.conf.j2 dest=/etc/krb5.conf
