- hosts: workers
  remote_user: bismart
  become: yes
  become_method: sudo

  tasks:

  - name: "Instalar paquete libselinux-python"
    yum: name=libselinux-python state=present

  - name: "Añadir disabled en ficchero SELINUX"
    selinux: state=disabled

  - name: "enforcing"
    command: "setenforce 0"
