
- hosts: {{ PLAYBOOK_HOSTS }}
  remote_user: bismart
  become: yes
  become_method: sudo

  tasks:
  - name: "Reemplazar fichero hosts"
    template:
      src=../templates/hosts.j2
      dest=/etc/hosts
      backup=true
      mode=0644
      owner=root
      group=root
