- hosts: workers
  remote_user: bismart
  become: yes
  become_method: sudo

  tasks:
  - name: "Reemplazar ficher resolv"
    template:
      src=../templates/resolv.conf.j2
      dest=/etc/resolv.conf
      backup=true
      mode=0644
      owner=root
      group=root
